const base = {
  publication: "Published",
  status: "Available",
  demo: true,
  featured: false,
  features: [],
  createdAt: "2026-09-01T00:00:00.000Z",
  location: "Nairobi, Kenya",
};
module.exports = [
  {
    id: "sample-new-parts",
    category: "part",
    title: "Engine service parts kit",
    condition: "New",
    price: 12500,
    quantity: 5,
    partNumber: "DEMO-KIT-001",
    brand: "Sample brand",
    partType: "Service kit",
    compatibility:
      "Illustrative listing. Confirm vehicle model, engine code, and fitment before ordering.",
    image: "/images/parts.jpg",
  },
  {
    id: "sample-used-parts",
    category: "part",
    title: "Used engine components",
    condition: "Used",
    price: 8500,
    quantity: 2,
    partNumber: "DEMO-ENG-002",
    brand: "Sample brand",
    partType: "Engine components",
    compatibility:
      "Illustrative listing. Actual parts and compatibility must be confirmed.",
    image: "/images/parts.jpg",
  },
  {
    id: "sample-plot",
    category: "land",
    title: "Residential plot",
    propertyType: "Plot",
    price: 1800000,
    area: 0.125,
    areaUnit: "Acres",
    tenure: "To be confirmed",
    image: "/images/land.jpg",
  },
  {
    id: "sample-land",
    category: "land",
    title: "Open land parcel",
    propertyType: "Land",
    price: 6500000,
    area: 2,
    areaUnit: "Acres",
    tenure: "To be confirmed",
    image: "/images/land.jpg",
  },
  {
    id: "sample-new-house",
    category: "house",
    title: "Contemporary family home",
    propertyType: "House",
    condition: "New",
    price: 18500000,
    bedrooms: 4,
    bathrooms: 3,
    area: 240,
    areaUnit: "Square metres",
    tenure: "To be confirmed",
    image: "/images/house-new.jpg",
  },
  {
    id: "sample-used-house",
    category: "house",
    title: "Established family residence",
    propertyType: "House",
    condition: "Used",
    price: 14000000,
    bedrooms: 3,
    bathrooms: 2,
    area: 190,
    areaUnit: "Square metres",
    tenure: "To be confirmed",
    image: "/images/house-used.jpg",
  },
].map((item) => ({
  ...base,
  ...item,
  images: [item.image],
  description:
    "Sample listing for the local preview only. Photography, prices, specifications, and location are illustrative. This is not an offer for an actual item or property.",
}));
