module.exports = [
  {
    id: "mercedes-amg-gt",
    make: "Mercedes-Benz",
    model: "AMG GT",
    year: 2019,
    price: 12950000,
    mileage: 48000,
    body: "Coupe",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "4.0L",
    color: "Silver",
    condition: "Foreign used",
    image: "/images/mercedes.jpg",
    featured: true,
    status: "Available",
    description:
      "Understated design, a comfortable cabin, and effortless everyday driving. This sample listing shows the level of detail you can expect when exploring a vehicle with Edwin.",
    features: [
      "Leather seats",
      "Reverse camera",
      "Cruise control",
      "Bluetooth",
      "Climate control",
      "Alloy wheels",
    ],
  },
  {
    id: "bmw-m3",
    make: "BMW",
    model: "M3",
    year: 2018,
    price: 6250000,
    mileage: 62000,
    body: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "3.0L",
    color: "Silver",
    condition: "Foreign used",
    image: "/images/bmw.jpg",
    featured: true,
    status: "Available",
    description:
      "A driver-focused sedan with a refined interior and a balanced feel on the road. Ask us about sourcing, inspection, and viewing arrangements.",
    features: [
      "Leather seats",
      "Parking sensors",
      "Cruise control",
      "Bluetooth",
      "Keyless entry",
      "Alloy wheels",
    ],
  },
  {
    id: "toyota-camry",
    make: "Toyota",
    model: "Camry",
    year: 2020,
    price: 2850000,
    mileage: 39000,
    body: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Silver",
    condition: "Foreign used",
    image: "/images/toyota.jpg",
    featured: true,
    status: "Available",
    description:
      "Spacious, comfortable, and ready for the everyday commute. A sample of the practical family vehicles you can explore with our team.",
    features: [
      "Reverse camera",
      "Bluetooth",
      "Climate control",
      "Cruise control",
      "USB ports",
      "Alloy wheels",
    ],
  },
  {
    id: "audi-rs7",
    make: "Audi",
    model: "RS7 Sportback",
    year: 2019,
    price: 11900000,
    mileage: 51000,
    body: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "4.0L",
    color: "Grey",
    condition: "Foreign used",
    image: "/images/audi.jpg",
    featured: false,
    status: "Available",
    description:
      "Distinctive styling with a quiet, thoughtfully appointed cabin. Contact the team for a conversation about the right specification for you.",
    features: [
      "Leather seats",
      "LED headlights",
      "Bluetooth",
      "Parking sensors",
      "Climate control",
      "Alloy wheels",
    ],
  },
  {
    id: "honda-crv",
    make: "Honda",
    model: "CR-V",
    year: 2018,
    price: 3150000,
    mileage: 73000,
    body: "SUV",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    condition: "Locally used",
    image: "/images/range-rover.jpg",
    featured: false,
    status: "Available",
    description:
      "An elevated driving position and a generous cabin for longer journeys. This illustrative listing can be replaced with your actual inventory in the admin dashboard.",
    features: [
      "Four-wheel drive",
      "Leather seats",
      "Panoramic roof",
      "Reverse camera",
      "Climate control",
      "Cruise control",
    ],
  },
  {
    id: "porsche-panamera",
    make: "Porsche",
    model: "Panamera",
    year: 2018,
    price: 12500000,
    mileage: 28000,
    body: "Sedan",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "3.0L",
    color: "Black",
    condition: "Foreign used",
    image: "/images/porsche.jpg",
    featured: false,
    status: "Reserved",
    description:
      "An unmistakable sports-car silhouette and an engaging driving experience. A sample premium listing, shown to help you explore the catalogue.",
    features: [
      "Leather seats",
      "Sport seats",
      "Navigation",
      "Parking sensors",
      "Climate control",
      "Alloy wheels",
    ],
  },
].map((car) => ({
  ...car,
  demo: true,
  images: [car.image],
  createdAt: "2026-09-01T00:00:00.000Z",
}));
